name: bongo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  provider: ^6.1.1
  pin_code_fields: ^8.0.1
  google_fonts: ^6.1.0
  go_router: ^13.0.1
  introduction_screen: ^3.1.12
  gap: ^3.0.1
  toastification: ^1.1.0
  flutter_carousel_widget: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
     - assets/
     - assets/images/
     - assets/images/onboarding/
     - assets/images/events/
     - assets/images/movies/
